// The link-preview image for grainlify.com: public/og-home.png, 1200x630.
//
//   npm run og-image
//
// Built the same way as the share cards in build.mjs - colours read from
// src/styles/brand.css, the real logo path, contrast audited, every element
// measured against the safe edge - so a preview never says something in
// colours or type the brand does not use.
//
// The words are the home page's own headline and its scope: both programmes
// that assign by draw. Nothing here states a number or a payout, because a
// preview image is cached by every site it is shared to and cannot be
// corrected afterwards.

import { mkdtempSync, writeFileSync, rmSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { chromium } from '@playwright/test'

import { ROLES } from './content.mjs'
import { auditContrast, esc, FONT_IMPORT, FONT_STACK, logo, renderOne, reportProblems, repoRoot, resolvePalette } from './lib.mjs'

const C = resolvePalette(ROLES, 'home preview image')

const W = 1200
const H = 630
const M = 88

const COPY = {
  headline: [
    { text: 'Funded issues aren’t first-come.', role: 'cream' },
    { text: 'A weighted draw assigns them.', role: 'gold' },
  ],
  support: ['GrainHack events and Grainlify Bounties, under rules', 'published before anyone applies.'],
  footer: 'grainlify.com',
}

const LAYOUT = {
  logoSize: 40,
  wordmarkSize: 30,
  headline: { size: 62, lineHeight: 78, firstBaseline: 250 },
  support: { size: 26, lineHeight: 36, firstBaseline: 418 },
  footer: { size: 22, baseline: 530 },
}

function svg() {
  const scale = LAYOUT.logoSize / logo.vbH
  const logoW = (LAYOUT.logoSize * logo.vbW) / logo.vbH
  const lines = (items, cls, first, step, fill) =>
    items.map((t, i) => `    <text class="${cls}" x="${M}" y="${first + i * step}" fill="${fill(t)}">${esc(t.text ?? t)}</text>`).join('\n')
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <!-- Generated by scripts/social-cards/og-home.mjs. Edit that file and re-run \`npm run og-image\`. -->
  <style>
    ${FONT_IMPORT}
    text { font-family: ${FONT_STACK}; }
    .wordmark { font-size: ${LAYOUT.wordmarkSize}px; font-weight: 600; letter-spacing: -0.01em; }
    .headline { font-size: ${LAYOUT.headline.size}px; font-weight: 700; letter-spacing: -0.022em; }
    .support  { font-size: ${LAYOUT.support.size}px; font-weight: 400; }
    .footer   { font-size: ${LAYOUT.footer.size}px; font-weight: 600; letter-spacing: 0.01em; }
  </style>
  <rect data-decorative="true" width="${W}" height="${H}" fill="${C.ground}"/>
  <g>
    <g transform="translate(${M}, ${M}) scale(${scale.toFixed(5)})"><path d="${logo.path}" fill="${C.gold}"/></g>
    <text class="wordmark" x="${M + logoW + 14}" y="${M + LAYOUT.logoSize / 2}" dominant-baseline="central" fill="${C.cream}">Grainlify</text>
${lines(COPY.headline, 'headline', LAYOUT.headline.firstBaseline, LAYOUT.headline.lineHeight, (l) => C[l.role])}
${lines(COPY.support, 'support', LAYOUT.support.firstBaseline, LAYOUT.support.lineHeight, () => C.support)}
    <text class="footer" x="${M}" y="${LAYOUT.footer.baseline}" fill="${C.gold}">${esc(COPY.footer)}</text>
  </g>
</svg>
`
}

auditContrast(
  [
    { what: 'wordmark', fg: C.cream, bg: C.ground, px: LAYOUT.wordmarkSize, bold: true },
    ...COPY.headline.map((l) => ({ what: `headline "${l.text}"`, fg: C[l.role], bg: C.ground, px: LAYOUT.headline.size, bold: true })),
    { what: 'supporting lines', fg: C.support, bg: C.ground, px: LAYOUT.support.size, bold: false },
    { what: 'footer', fg: C.gold, bg: C.ground, px: LAYOUT.footer.size, bold: false },
    { what: 'logo mark', fg: C.gold, bg: C.ground, px: LAYOUT.logoSize, graphic: true },
  ],
  'home preview image',
)

const tmp = mkdtempSync(path.join(os.tmpdir(), 'og-home-'))
const svgPath = path.join(tmp, 'og-home.svg')
writeFileSync(svgPath, svg())
const pngPath = path.join(repoRoot, 'public', 'og-home.png')

const browser = await chromium.launch()
try {
  // Scale 1: the file is served as the preview itself, at exactly 1200x630.
  const { boxes, usedInter } = await renderOne(browser, { svgPath, pngPath, width: W, height: H, scale: 1 })
  const problems = []
  if (usedInter === false) problems.push('Inter did not load; the preview would ship in a fallback font.')
  for (const b of boxes) {
    if (b.left < M || b.right > W - M || b.top < M || b.bottom > H - M) {
      problems.push(`"${b.label}" crosses the ${M}px safe edge: ${JSON.stringify(b)}`)
    }
  }
  if (reportProblems(problems, 'Shorten the copy or move the baselines in og-home.mjs.')) process.exitCode = 1
  else console.log(`\nWrote ${path.relative(repoRoot, pngPath)} (${W}x${H}).`)
} finally {
  await browser.close()
  rmSync(tmp, { recursive: true, force: true })
}
